[project]
name = "sps-data"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "camelot-py>=0.11.0",
    "ghostscript>=0.7",
    "opencv-python>=4.10.0.84",
    "pdfquery>=0.4.3",
]
